export const CURRENCY_LIST = [
  { code: "USD", symbol: "$", name: "United States Dollar (USD $)" },
  { code: "PKR", symbol: "Rs", name: "Pakistani Rupee (PKR Rs)" },
  { code: "EUR", symbol: "€", name: "Euro (EUR €)" },
  { code: "GBP", symbol: "£", name: "British Pound (GBP £)" },
  { code: "INR", symbol: "₹", name: "Indian Rupee (INR ₹)" },
  { code: "AED", symbol: "AED", name: "United Arab Emirates Dirham (AED)" },
  { code: "SAR", symbol: "SAR", name: "Saudi Riyal (SAR)" },
  { code: "CAD", symbol: "CA$", name: "Canadian Dollar (CAD CA$)" },
  { code: "AUD", symbol: "AU$", name: "Australian Dollar (AUD AU$)" },
  { code: "SGD", symbol: "SG$", name: "Singapore Dollar (SGD SG$)" },
  { code: "JPY", symbol: "¥", name: "Japanese Yen (JPY ¥)" },
  { code: "CNY", symbol: "¥", name: "Chinese Yuan (CNY ¥)" },
  { code: "BRL", symbol: "R$", name: "Brazilian Real (BRL R$)" },
  { code: "ZAR", symbol: "R", name: "South African Rand (ZAR R)" },
  { code: "TRY", symbol: "₺", name: "Turkish Lira (TRY ₺)" },
  { code: "EGP", symbol: "E£", name: "Egyptian Pound (EGP E£)" },
  { code: "KWD", symbol: "KWD", name: "Kuwaiti Dinar (KWD)" },
  { code: "QAR", symbol: "QAR", name: "Qatari Riyal (QAR)" },
  { code: "OMR", symbol: "OMR", name: "Omani Rial (OMR)" },
  { code: "BHD", symbol: "BHD", name: "Bahraini Dinar (BHD)" },
  { code: "MYR", symbol: "RM", name: "Malaysian Ringgit (MYR RM)" },
  { code: "THB", symbol: "฿", name: "Thai Baht (THB ฿)" },
  { code: "IDR", symbol: "Rp", name: "Indonesian Rupiah (IDR Rp)" },
  { code: "PHP", symbol: "₱", name: "Philippine Peso (PHP ₱)" },
  { code: "NGN", symbol: "₦", name: "Nigerian Naira (NGN ₦)" },
  { code: "KES", symbol: "KSh", name: "Kenyan Shilling (KES KSh)" },
  { code: "BDT", symbol: "৳", name: "Bangladeshi Taka (BDT ৳)" },
  { code: "LKR", symbol: "Rs", name: "Sri Lankan Rupee (LKR Rs)" },
  { code: "NZD", symbol: "NZ$", name: "New Zealand Dollar (NZD NZ$)" },
  { code: "CHF", symbol: "CHF", name: "Swiss Franc (CHF)" },
  { code: "SEK", symbol: "kr", name: "Swedish Krona (SEK kr)" },
  { code: "NOK", symbol: "kr", name: "Norwegian Krone (NOK kr)" },
  { code: "DKK", symbol: "kr", name: "Danish Krone (DKK kr)" },
  { code: "PLN", symbol: "zł", name: "Polish Zloty (PLN zł)" },
  { code: "RUB", symbol: "₽", name: "Russian Ruble (RUB ₽)" },
];
