/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EmbedIdRouteImport } from './routes/embed.$id'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard.templates'
import { Route as DashboardTelegramRouteImport } from './routes/dashboard.telegram'
import { Route as DashboardStorageRouteImport } from './routes/dashboard.storage'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardScriptsRouteImport } from './routes/dashboard.scripts'
import { Route as DashboardInboxRouteImport } from './routes/dashboard.inbox'
import { Route as DashboardFaqRouteImport } from './routes/dashboard.faq'
import { Route as DashboardCreateRouteImport } from './routes/dashboard.create'
import { Route as CheckoutPlanIdRouteImport } from './routes/checkout.$planId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStorageRouteImport } from './routes/admin.storage'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPurchasesRouteImport } from './routes/admin.purchases'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminChatbotsRouteImport } from './routes/admin.chatbots'

const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EmbedIdRoute = EmbedIdRouteImport.update({
  id: '/embed/$id',
  path: '/embed/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTelegramRoute = DashboardTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStorageRoute = DashboardStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScriptsRoute = DashboardScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInboxRoute = DashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFaqRoute = DashboardFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreateRoute = DashboardCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DashboardRoute,
} as any)
const CheckoutPlanIdRoute = CheckoutPlanIdRouteImport.update({
  id: '/checkout/$planId',
  path: '/checkout/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStorageRoute = AdminStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPurchasesRoute = AdminPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatbotsRoute = AdminChatbotsRouteImport.update({
  id: '/chatbots',
  path: '/chatbots',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/plans': typeof PlansRoute
  '/admin/chatbots': typeof AdminChatbotsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/faq': typeof DashboardFaqRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/scripts': typeof DashboardScriptsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/telegram': typeof DashboardTelegramRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/embed/$id': typeof EmbedIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plans': typeof PlansRoute
  '/admin/chatbots': typeof AdminChatbotsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/faq': typeof DashboardFaqRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/scripts': typeof DashboardScriptsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/telegram': typeof DashboardTelegramRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/embed/$id': typeof EmbedIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/plans': typeof PlansRoute
  '/admin/chatbots': typeof AdminChatbotsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/faq': typeof DashboardFaqRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/scripts': typeof DashboardScriptsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/telegram': typeof DashboardTelegramRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/embed/$id': typeof EmbedIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/plans'
    | '/admin/chatbots'
    | '/admin/plans'
    | '/admin/products'
    | '/admin/purchases'
    | '/admin/settings'
    | '/admin/storage'
    | '/admin/users'
    | '/checkout/$planId'
    | '/dashboard/create'
    | '/dashboard/faq'
    | '/dashboard/inbox'
    | '/dashboard/scripts'
    | '/dashboard/settings'
    | '/dashboard/storage'
    | '/dashboard/telegram'
    | '/dashboard/templates'
    | '/embed/$id'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/plans'
    | '/admin/chatbots'
    | '/admin/plans'
    | '/admin/products'
    | '/admin/purchases'
    | '/admin/settings'
    | '/admin/storage'
    | '/admin/users'
    | '/checkout/$planId'
    | '/dashboard/create'
    | '/dashboard/faq'
    | '/dashboard/inbox'
    | '/dashboard/scripts'
    | '/dashboard/settings'
    | '/dashboard/storage'
    | '/dashboard/telegram'
    | '/dashboard/templates'
    | '/embed/$id'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/plans'
    | '/admin/chatbots'
    | '/admin/plans'
    | '/admin/products'
    | '/admin/purchases'
    | '/admin/settings'
    | '/admin/storage'
    | '/admin/users'
    | '/checkout/$planId'
    | '/dashboard/create'
    | '/dashboard/faq'
    | '/dashboard/inbox'
    | '/dashboard/scripts'
    | '/dashboard/settings'
    | '/dashboard/storage'
    | '/dashboard/telegram'
    | '/dashboard/templates'
    | '/embed/$id'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  PlansRoute: typeof PlansRoute
  CheckoutPlanIdRoute: typeof CheckoutPlanIdRoute
  EmbedIdRoute: typeof EmbedIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/embed/$id': {
      id: '/embed/$id'
      path: '/embed/$id'
      fullPath: '/embed/$id'
      preLoaderRoute: typeof EmbedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/telegram': {
      id: '/dashboard/telegram'
      path: '/telegram'
      fullPath: '/dashboard/telegram'
      preLoaderRoute: typeof DashboardTelegramRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/storage': {
      id: '/dashboard/storage'
      path: '/storage'
      fullPath: '/dashboard/storage'
      preLoaderRoute: typeof DashboardStorageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/scripts': {
      id: '/dashboard/scripts'
      path: '/scripts'
      fullPath: '/dashboard/scripts'
      preLoaderRoute: typeof DashboardScriptsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inbox': {
      id: '/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof DashboardInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/faq': {
      id: '/dashboard/faq'
      path: '/faq'
      fullPath: '/dashboard/faq'
      preLoaderRoute: typeof DashboardFaqRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/create': {
      id: '/dashboard/create'
      path: '/create'
      fullPath: '/dashboard/create'
      preLoaderRoute: typeof DashboardCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/checkout/$planId': {
      id: '/checkout/$planId'
      path: '/checkout/$planId'
      fullPath: '/checkout/$planId'
      preLoaderRoute: typeof CheckoutPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/storage': {
      id: '/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AdminStorageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/purchases': {
      id: '/admin/purchases'
      path: '/purchases'
      fullPath: '/admin/purchases'
      preLoaderRoute: typeof AdminPurchasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chatbots': {
      id: '/admin/chatbots'
      path: '/chatbots'
      fullPath: '/admin/chatbots'
      preLoaderRoute: typeof AdminChatbotsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminChatbotsRoute: typeof AdminChatbotsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminPurchasesRoute: typeof AdminPurchasesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStorageRoute: typeof AdminStorageRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChatbotsRoute: AdminChatbotsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminPurchasesRoute: AdminPurchasesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStorageRoute: AdminStorageRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardCreateRoute: typeof DashboardCreateRoute
  DashboardFaqRoute: typeof DashboardFaqRoute
  DashboardInboxRoute: typeof DashboardInboxRoute
  DashboardScriptsRoute: typeof DashboardScriptsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStorageRoute: typeof DashboardStorageRoute
  DashboardTelegramRoute: typeof DashboardTelegramRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCreateRoute: DashboardCreateRoute,
  DashboardFaqRoute: DashboardFaqRoute,
  DashboardInboxRoute: DashboardInboxRoute,
  DashboardScriptsRoute: DashboardScriptsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStorageRoute: DashboardStorageRoute,
  DashboardTelegramRoute: DashboardTelegramRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  PlansRoute: PlansRoute,
  CheckoutPlanIdRoute: CheckoutPlanIdRoute,
  EmbedIdRoute: EmbedIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
